# Author configs
title:       "The Red Panda"
email:       "yagosansz@gmail.com"
author:      "Yago Santos"
avatar:      "./assets/avatar.jpeg"
location:    "Hamilton - ON, Canada"
description: "I've created this blog to document my learning journey as a Software Developer."

# Other configs
skin:       "sunrise"
pagination: 5
subscribe: false
baseurl:    ""
url:        "" 


# Build settings
remote_theme: ngzhio/jekyll-theme-hamilton
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
